#GENBUCKETS

genbucket:
  cobble:
    slot: 2
    name: '&4&lCobble genbucket'
    price: 50000
    amount: 10
    lores:
    - '&2Click here to generate a cobble pillar'
    - '&2at the desired location.'
  obsdian:
    slot: 3
    name: '&4&lObsdian genbucket'
    price: 50000
    amount: 10
    lores:
    - '&2Click here to generate a obsdian pillar'
    - '&2at the desired location.'
gui:
    name: '&5GenBuckets'
    buy_message: '&5You have bought a genbucket'
    not_enough_money: '&4You do not have enough money to buy'
    inv_full: '&4 Your inventory is full!'